### ISSUE TITLE
/landscapeapp/public/settings.json missing?

### ISSUE THREAD

**Issue by 3213-cmd** [opendatahub-io/odh-landscape#5]
**Describe the bug**
I have followed the instructions provided here: https://github.com/opendatahub-io/odh-landscape/blob/master/INSTALL.md (everything except the script, since it is not available anymore,  but I believe it is not necesarry since I ran other forks of the landscapeapp without issues). But when I run the make dev command and try to access the local landscape I get the following error:

`./src/pages/_app.js:7:0
Module not found: Can't resolve '/home/user/MyProjects/landscape2/landscapeapp/public/settings.json'
   5 | import '../styles/theme.css'
   6 | import '../styles/itemModal.css'
>  7 | import settings from 'public/settings.json';
   8 | import ReactGA from 'react-ga';
   9 | import iframeResizerContentWindow from 'iframe-resizer/js/iframeResizer.contentWindow';
  10 | import { useEffect, useState } from 'react'`

**ODH Landscape Version**
Using the latest version

Any help would be appreciated.

**Comment by sibaev** [comment]
I apologize, it is working. I didn't notice that an error occured, during the build step. Changing my Node version fixed it. I switched to 16.20 , 12 was too low, 20 too high.
